### ISSUE TITLE
not support Android 13, pls update

### ISSUE THREAD

**Issue by zilinhero** [Xposed-Modules-Repo/com.metris.xposed.pmods#1]
not support Android 13, pls update

**Comment by Massi-X** [comment]
Hi please report issues at https://forum.xda-developers.com/t/pixel-mods-hide-apps-from-the-pixel-launcher-xposed.4288973/ or better directly pm me with the log attached.

As a side note it works for me and others on A13, I have to look why it doesn't work for you.
